question_data = [
{"question": "A slug's blood is green.", "answer": "True"},
{"question": "The loudest animal is the African Elephant.", "answer": "False"},
{"question": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
{"question": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
{"question": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
{"question": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
{"question": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
{"question": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
{"question": "Google was originally called 'Backrub'.", "answer": "True"},
{"question": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
{"question": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
{"question": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
]

computer_science_data = [
    {"category": "Science: Computers",
     "type": "boolean",
     "difficulty": "easy",
     "question": "Linus Torvalds created Linux and Git.",
     "answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The programming language Python is based off a modified version of JavaScript.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The logo for Snapchat is a Bell.", "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Ada Lovelace is often considered the first computer programmer.", "answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "In most programming languages, the operator ++ is equivalent to the statement += 1.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Time on Computers is measured via the EPOX System.", "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The Windows ME operating system was released in the year 2000.",
     "answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
     "answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Linux was first created as an alternative to Windows XP.", "answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The Python programming language gets its name from the British comedy group Monty Python.",
     "answer": "True", "incorrect_answers": ["False"]}]
